---
- name: Change vm hostname
  hostname: 
    name: '{{inventory_hostname}}'
    
- name: Add GPG key
  command: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Copy Elastic.repo to VM
  template:
    src: /home/ec2-user/ansible/roles/elasticsearchz2/templates/elastic.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
  register: elastic_repo

- name: Install ElasticSearch
  yum:
      name: elasticsearch
      state: latest

- name: Create Master config file
  template:
    src: /home/ec2-user/ansible/roles/elasticsearchz2/templates/configMaster.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: 0660
  register: elastic_yml
  when: inventory_hostname == "{{groups.elasticz1[0]}}"

- name: Create Slave config file
  template:
    src: /home/ec2-user/ansible/roles/elasticsearchz2/templates/configSlave.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: 0660
  register: elastic_yml
  when: inventory_hostname != "{{groups.elasticz1[0]}}"

- name: Create config file
  template:
    src: /home/ec2-user/ansible/roles/elasticsearchz2/templates/jvm.j2
    dest: /etc/elasticsearch/jvm.options
    owner: elasticsearch
    group: elasticsearch
    mode: 0660
  register: jvm

- name: Install plugin
  shell: "echo y | sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install discovery-ec2 -s"

- name: reload systemd config
  systemd: daemon_reload=yes

- name: Start ElasticSearch
  service: name=elasticsearch state=started enabled=yes
