---
- name: Change vm hostname
  hostname: 
    name: '{{inventory_hostname}}'

- name: Install Epel-release
  shell: sudo amazon-linux-extras install epel -y

- name: Install Nginx and Pacemaker services
  yum:
    name:
      - nginx 
      - resource-agents
    state: present
  register: install

- name: Generate Nginx config file
  template: 
    src: /home/ec2-user/ansible/roles/nginx/templates/nginx.j2 
    dest: /etc/nginx/nginx.conf

- name: Start Nginx services
  service: name=nginx state=started enabled=yes
