---
- name: Install Java
  hosts: all
  become: yes

  roles:
   - java

- name: Install FileBeat at z1
  hosts: nginx
  become: yes

  roles:
   - filebeat

# - name: Install FileBeat at z2
#   hosts: nginx
#   become: yes

#   roles:
#    - filebeatz2

- name: Install Nginx
  hosts: nginxALL
  become: yes

  roles:
   - nginx

- name: Install Kibana
  hosts: kibana
  become: yes

  roles:
    - kibana 

- name: Install Logstash
  hosts: logALL
  become: yes
  
  roles:
   - logstash

- name: Install ElasticSearch at Z1
  hosts: elasticz1
  become: yes

  roles:
    - elasticsearch

- name: Install ElasticSearch at Z2
  hosts: elasticz2
  become: yes

  roles:
    - elasticsearchz2

