---
# - name: Install Java
#   hosts: all
#   become: yes

#   roles:
#    - java

# - name: Install FileBeat at z1
#   hosts: all
#   become: yes

#   roles:
#    - filebeat

# - name: Install FileBeat at z2
#   hosts: all
#   become: yes

#   roles:
#    - filebeatz2

# - name: Install Nginx
#   hosts: nginxALL
#   become: yes

#   roles:
#    - nginx

# - name: Install Kibana
#   hosts: kibana
#   become: yes

#   roles:
#     - kibana 

# - name: Install Logstash
#   hosts: logALL
#   become: yes
  
#   roles:
#    - logstash

- name: Install ElasticSearch
  hosts: elasticALL
  become: yes

  roles:
    - elasticsearch

