---
- name: Install Nginx
  hosts: kibana
  become: yes

  roles:
   - nginx
   
- name: Install Kibana
  hosts: kibana
  become: yes

  roles:
    - kibana 

- name: Install Logstash
  hosts: log
  become: yes
  
  roles:
   - logstash

- name: Install ElasticSearch
  hosts: elastic
  become: yes

  roles:
    - elasticsearch

- name: Install FileBeat
  hosts: all
  become: yes

  roles:
   - filebeat
